### ISSUE TITLE
Non public init

### ISSUE THREAD

**Issue by Keloran** [elliottminns/orca-mongodb#1]
Compiling Swift Module 'Site' (3 sources)
/root/code/website/blackfish/Sources/main.swift:6:13: error: 'OrcaMongoDB' initializer is inaccessible due to 'internal' protection level
let mongo = OrcaMongoDB()
            ^
<unknown>:0: note: 'init' declared here
<unknown>:0: error: build had 1 command failures

**Comment by elliottminns** [comment]
Ahh, my mistake. I was up til quite late getting it to work for Linux and must have missed this. 

I'll push a hot fix in the next hour

**Comment by elliottminns** [comment]
Fixed here: 3940c79147ff53271f91b91ecc0fa0fe52af9757

**Comment by Keloran** [comment]
thanks
